//Project Includes
#include "../logging/logging.h"

//Dep Includes
#include <string>
#include <array>

enum InputVars
{
    CurrentFoodMagnitude = 0,
    ColonyFoodMagnitude,
    Age,
    InverseAge,
    MovingPersonalFoodTrend,
    LifetimePersonalFoodTrend,
    MovingColonyFoodTrend,
    LifetimeColonyFoodTrend,
    PersonalTimerA,
    PersonalTimerB,
    ColonyTimerA,
    ColonyTimerB,
    TileTypeO,
    TileTypePP,
    TileTypePN,
    TileTypeNP,
    TileTypeNN,
    TileHeightO,
    TileHeightPP,
    TileHeightPN,
    TileHeightNP,
    TileHeightNN,
    TileAntCountO,
    TileAntCountPP,
    TileAntCountPN,
    TileAntCountNP,
    TileAntCountNN,
    PersonalDecayingMemoryA,
    PersonalDecayingMemoryB,
    PersonalDecayingMemoryC,
    PersonalDecayingMemoryD,
    PersonalStaticMemoryA,
    PersonalStaticMemoryB,
    PersonalStaticMemoryC,
    PersonalStaticMemoryD,
    ColonyStaticMemoryA,
    ColonyStaticMemoryB,
    ColonyStaticMemoryC,
    ColonyStaticMemoryD,
    PersonalPassiveScentO,
    PersonalPassiveScentPP,
    PersonalPassiveScentPN,
    PersonalPassiveScentNP,
    PersonalPassiveScentNN,
    PersonalActiveScentAO,
    PersonalActiveScentAPP,
    PersonalActiveScentAPN,
    PersonalActiveScentANP,
    PersonalActiveScentANN,
    PersonalActiveScentBO,
    PersonalActiveScentBPP,
    PersonalActiveScentBPN,
    PersonalActiveScentBNP,
    PersonalActiveScentBNN,
    ColonyPassiveScentO,
    ColonyPassiveScentPP,
    ColonyPassiveScentPN,
    ColonyPassiveScentNP,
    ColonyPassiveScentNN,
    ColonyActiveScentCO,
    ColonyActiveScentCPP,
    ColonyActiveScentCPN,
    ColonyActiveScentCNP,
    ColonyActiveScentCNN
};

enum OutputActions
{
    NoOP = 0,
    MoveUP,
    MoveDOWN,
    MoveLEFT,
    MoveRIGHT,
    HarvestFood,
    GiveFood,
    TakeFood,
    WorkTile,
    CultivateTile,
    BuildRoad,
    RaiseHeight,
    LowerHeight,
    ProduceOffspring,
    ADecrementPDMA,
    BDecrementPDMA,
    AIncrementPDMA,
    BIncrementPDMA,
    ADecrementPDMB,
    BDecrementPDMB,
    AIncrementPDMB,
    BIncrementPDMB,
    ADecrementPDMC,
    BDecrementPDMC,
    AIncrementPDMC,
    BIncrementPDMC,
    ADecrementPDMD,
    BDecrementPDMD,
    AIncrementPDMD,
    BIncrementPDMD,
    ADecrementPSMA,
    BDecrementPSMA,
    AIncrementPSMA,
    BIncrementPSMA,
    ADecrementPSMB,
    BDecrementPSMB,
    AIncrementPSMB,
    BIncrementPSMB,
    ADecrementPSMC,
    BDecrementPSMC,
    AIncrementPSMC,
    BIncrementPSMC,
    ADecrementPSMD,
    BDecrementPSMD,
    AIncrementPSMD,
    BIncrementPSMD,
    VoteIncrementCSMA,
    VoteIncrementCSMB,
    VoteIncrementCSMC,
    VoteIncrementCSMD,
    VoteDecrementCSMA,
    VoteDecrementCSMB,
    VoteDecrementCSMC,
    VoteDecrementCSMD,
    ReleaseSmallScentA,
    ReleaseLargeScentA,
    ReleaseSmallScentB,
    ReleaseLargeScentB,
    ReleaseSmallScentC,
    ReleaseLargeScentC,
    ResetPersonalTimerA,
    ResetPersonalTimerB,
    VoteResetColonyTimerA,
    VoteResetColonyTimerB
};

class AI
{
  private:
  public:
    AI() { };                          //Builds random
    AI(std::string geneticString) { }; //Builds from genetic string
    virtual OutputActions get(std::array<unsigned char, 64> input);
};